class RoyalcirqueMailer < ActionMailer::Base

  def mail_royal_cirque(name,email,message)
    @name = "#{name}"
    @email = "#{email}"
    @sub = "Contact Message"
    @message = "#{message}"

    mail(to: "info@royalcirquepub.com", from: "contact@royalcirquepub.com", subject: 'Autogenerated Mail From Royal Cirque Contact Page')
  end

  def order_received(customer, order)
    @name = "#{customer.first_name} #{customer.last_name}"
    @email = "#{customer.email}"
    @sub = "Order Received"
    @order = order

    mail(to: "info@royalcirquepub.com", from: "order@royalcirquepub.com", subject: 'Autogenerated Mail From Royal Cirque Order')
  end
end
