class RoyalcirqueMailer < ActionMailer::Base

  def mail_royal_cirque(name,email,message)
    # @from = "#{email}"
    # @recipients = "info@royalcirquepub.com"
    # @subject = "Autogenerated Mail From Royal Cirque Contact Page"
    # @content_type = 'text/html'

    mail(to: "info@royalcirquepub.com", from: email, subject: 'Autogenerated Mail From Royal Cirque Contact Page')

    @name = "#{name}"
    @email = "#{email}"
    @sub = "Contact Message"
    @message = "#{message}"
  end

  def order_received(customer, order)
    mail(to: "info@royalcirquepub.com", from: "order@royalcirquepub.com", subject: 'Autogenerated Mail From Royal Cirque Order')

    # @from = "order@royalcirquepub.com"
    # @recipients = "info@royalcirquepub.com"
    # @subject = "Autogenerated Mail From Royal Cirque Order"
    # @content_type = 'text/html'
    @name = "#{customer.first_name} #{customer.last_name}"
    @email = "#{customer.email}"
    @sub = "Order Received"
    @order = order
  end
end
