class RoyalcirqueMailer < ActionMailer::Base
  
  def mail(name,email,message)
    @from = "#{email}"
    @recipients = "info@royalcirquepub.com"
    @subject = "Autogenerated Mail From Royal Cirque Contact Page"
    @content_type = 'text/html'
    @body[:name] = "#{name}"
    @body[:email] = "#{email}"
    @body[:sub] = "Contact Message"
    @body[:message] = "#{message}"
  end  

  def order_received(customer, order)
    @from = "order@royalcirquepub.com"
    @recipients = "info@royalcirquepub.com"
    @subject = "Autogenerated Mail From Royal Cirque Order"
    @content_type = 'text/html'
    @body[:name] = "#{customer.first_name} #{customer.last_name}"
    @body[:email] = "#{customer.email}"
    @body[:sub] = "Order Received"
    @body[:order] = order
  end  
end
