class RoyalcirqueMailer < ActionMailer::Base
  
  def mail(name,email,message)
    @from = "#{email}"
    @recipients = "info@royalcirquepub.com"
    @subject = "Autogenerated Mail From Royal Cirque Contact Page"
    @content_type = 'text/html'
    @body[:name] = "#{name}"
    @body[:email] = "#{email}"
    @body[:sub] = "Contact Message"
    @body[:message] = "#{message}"
  end  

end
